/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaixaRouteImport } from './routes/caixa'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as CasaRouteImport } from './routes/casa'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as GovernancaRouteImport } from './routes/governanca'
import { Route as HospedesRouteImport } from './routes/hospedes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OcupacaoRouteImport } from './routes/ocupacao'
import { Route as OfertasRouteImport } from './routes/ofertas'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as ReservarRouteImport } from './routes/reservar'
import { Route as ReservasRouteImport } from './routes/reservas'
import { Route as ReservasDiretasRouteImport } from './routes/reservas-diretas'
import { Route as TarifasRouteImport } from './routes/tarifas'
import { Route as HospedesGuestIdRouteImport } from './routes/hospedes.$guestId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaixaRoute = CaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const CasaRoute = CasaRouteImport.update({
  id: '/casa',
  path: '/casa',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernancaRoute = GovernancaRouteImport.update({
  id: '/governanca',
  path: '/governanca',
  getParentRoute: () => rootRouteImport,
} as any)
const HospedesRoute = HospedesRouteImport.update({
  id: '/hospedes',
  path: '/hospedes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OcupacaoRoute = OcupacaoRouteImport.update({
  id: '/ocupacao',
  path: '/ocupacao',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertasRoute = OfertasRouteImport.update({
  id: '/ofertas',
  path: '/ofertas',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservarRoute = ReservarRouteImport.update({
  id: '/reservar',
  path: '/reservar',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservasRoute = ReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservasDiretasRoute = ReservasDiretasRouteImport.update({
  id: '/reservas-diretas',
  path: '/reservas-diretas',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifasRoute = TarifasRouteImport.update({
  id: '/tarifas',
  path: '/tarifas',
  getParentRoute: () => rootRouteImport,
} as any)
const HospedesGuestIdRoute = HospedesGuestIdRouteImport.update({
  id: '/$guestId',
  path: '/$guestId',
  getParentRoute: () => HospedesRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/caixa': typeof CaixaRoute
  '/calendario': typeof CalendarioRoute
  '/casa': typeof CasaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/equipe': typeof EquipeRoute
  '/governanca': typeof GovernancaRoute
  '/hospedes': typeof HospedesRouteWithChildren
  '/login': typeof LoginRoute
  '/ocupacao': typeof OcupacaoRoute
  '/ofertas': typeof OfertasRoute
  '/relatorios': typeof RelatoriosRoute
  '/reservar': typeof ReservarRoute
  '/reservas': typeof ReservasRoute
  '/reservas-diretas': typeof ReservasDiretasRoute
  '/tarifas': typeof TarifasRoute
  '/hospedes/$guestId': typeof HospedesGuestIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/caixa': typeof CaixaRoute
  '/calendario': typeof CalendarioRoute
  '/casa': typeof CasaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/equipe': typeof EquipeRoute
  '/governanca': typeof GovernancaRoute
  '/hospedes': typeof HospedesRouteWithChildren
  '/login': typeof LoginRoute
  '/ocupacao': typeof OcupacaoRoute
  '/ofertas': typeof OfertasRoute
  '/relatorios': typeof RelatoriosRoute
  '/reservar': typeof ReservarRoute
  '/reservas': typeof ReservasRoute
  '/reservas-diretas': typeof ReservasDiretasRoute
  '/tarifas': typeof TarifasRoute
  '/hospedes/$guestId': typeof HospedesGuestIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/caixa': typeof CaixaRoute
  '/calendario': typeof CalendarioRoute
  '/casa': typeof CasaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/equipe': typeof EquipeRoute
  '/governanca': typeof GovernancaRoute
  '/hospedes': typeof HospedesRouteWithChildren
  '/login': typeof LoginRoute
  '/ocupacao': typeof OcupacaoRoute
  '/ofertas': typeof OfertasRoute
  '/relatorios': typeof RelatoriosRoute
  '/reservar': typeof ReservarRoute
  '/reservas': typeof ReservasRoute
  '/reservas-diretas': typeof ReservasDiretasRoute
  '/tarifas': typeof TarifasRoute
  '/hospedes/$guestId': typeof HospedesGuestIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/caixa'
    | '/calendario'
    | '/casa'
    | '/configuracoes'
    | '/equipe'
    | '/governanca'
    | '/hospedes'
    | '/login'
    | '/ocupacao'
    | '/ofertas'
    | '/relatorios'
    | '/reservar'
    | '/reservas'
    | '/reservas-diretas'
    | '/tarifas'
    | '/hospedes/$guestId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/caixa'
    | '/calendario'
    | '/casa'
    | '/configuracoes'
    | '/equipe'
    | '/governanca'
    | '/hospedes'
    | '/login'
    | '/ocupacao'
    | '/ofertas'
    | '/relatorios'
    | '/reservar'
    | '/reservas'
    | '/reservas-diretas'
    | '/tarifas'
    | '/hospedes/$guestId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/caixa'
    | '/calendario'
    | '/casa'
    | '/configuracoes'
    | '/equipe'
    | '/governanca'
    | '/hospedes'
    | '/login'
    | '/ocupacao'
    | '/ofertas'
    | '/relatorios'
    | '/reservar'
    | '/reservas'
    | '/reservas-diretas'
    | '/tarifas'
    | '/hospedes/$guestId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaixaRoute: typeof CaixaRoute
  CalendarioRoute: typeof CalendarioRoute
  CasaRoute: typeof CasaRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  EquipeRoute: typeof EquipeRoute
  GovernancaRoute: typeof GovernancaRoute
  HospedesRoute: typeof HospedesRouteWithChildren
  LoginRoute: typeof LoginRoute
  OcupacaoRoute: typeof OcupacaoRoute
  OfertasRoute: typeof OfertasRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ReservarRoute: typeof ReservarRoute
  ReservasRoute: typeof ReservasRoute
  ReservasDiretasRoute: typeof ReservasDiretasRoute
  TarifasRoute: typeof TarifasRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caixa': {
      id: '/caixa'
      path: '/caixa'
      fullPath: '/caixa'
      preLoaderRoute: typeof CaixaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casa': {
      id: '/casa'
      path: '/casa'
      fullPath: '/casa'
      preLoaderRoute: typeof CasaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governanca': {
      id: '/governanca'
      path: '/governanca'
      fullPath: '/governanca'
      preLoaderRoute: typeof GovernancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospedes': {
      id: '/hospedes'
      path: '/hospedes'
      fullPath: '/hospedes'
      preLoaderRoute: typeof HospedesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocupacao': {
      id: '/ocupacao'
      path: '/ocupacao'
      fullPath: '/ocupacao'
      preLoaderRoute: typeof OcupacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ofertas': {
      id: '/ofertas'
      path: '/ofertas'
      fullPath: '/ofertas'
      preLoaderRoute: typeof OfertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservar': {
      id: '/reservar'
      path: '/reservar'
      fullPath: '/reservar'
      preLoaderRoute: typeof ReservarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservas': {
      id: '/reservas'
      path: '/reservas'
      fullPath: '/reservas'
      preLoaderRoute: typeof ReservasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservas-diretas': {
      id: '/reservas-diretas'
      path: '/reservas-diretas'
      fullPath: '/reservas-diretas'
      preLoaderRoute: typeof ReservasDiretasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifas': {
      id: '/tarifas'
      path: '/tarifas'
      fullPath: '/tarifas'
      preLoaderRoute: typeof TarifasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospedes/$guestId': {
      id: '/hospedes/$guestId'
      path: '/$guestId'
      fullPath: '/hospedes/$guestId'
      preLoaderRoute: typeof HospedesGuestIdRouteImport
      parentRoute: typeof HospedesRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HospedesRouteChildren {
  HospedesGuestIdRoute: typeof HospedesGuestIdRoute
}

const HospedesRouteChildren: HospedesRouteChildren = {
  HospedesGuestIdRoute: HospedesGuestIdRoute,
}

const HospedesRouteWithChildren = HospedesRoute._addFileChildren(
  HospedesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaixaRoute: CaixaRoute,
  CalendarioRoute: CalendarioRoute,
  CasaRoute: CasaRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  EquipeRoute: EquipeRoute,
  GovernancaRoute: GovernancaRoute,
  HospedesRoute: HospedesRouteWithChildren,
  LoginRoute: LoginRoute,
  OcupacaoRoute: OcupacaoRoute,
  OfertasRoute: OfertasRoute,
  RelatoriosRoute: RelatoriosRoute,
  ReservarRoute: ReservarRoute,
  ReservasRoute: ReservasRoute,
  ReservasDiretasRoute: ReservasDiretasRoute,
  TarifasRoute: TarifasRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
